//GAME
export const TIMER_TICK = 'TIMER_TICK';
export const STARS_NEW_RANDOM = 'STARS_NEW_RANDOM';
export const UPDATE_AVAILABLE_NUMBERS = 'UPDATE_AVAILABLE_NUMBERS';
export const UPDATE_CANDIDATE_NUMBERS = 'UPDATE_CANDIDATE_NUMBERS';
export const CHANGE_DIFFICULTY_LEVEL = 'CHANGE_DIFFICULTY_LEVEL';

// HIGHSCORES
export const FETCH_HIGHSCORE = 'FETCH_HIGHSCORE';
export const FETCH_HIGHSCORE_SUCEEDED = 'FETCH_HIGHSCORE_SUCEEDED';
export const FETCH_HIGHSCORE_FAILED = 'FETCH_HIGHSCORE_FAILED';

// SAVE SCORE
export const SAVE_SCORE = 'SAVE_SCORE';
export const SAVE_SCORE_SUCCEDEED = 'SAVE_SCORE_SUCCEDEED';
export const SAVE_SCORE_FAILED = 'SAVE_SCORE_FAILED';
export const RESET_SAVE_SCORE = 'RESET_SAVE_SCORE';
