//GAME
export const TIMER_TICK = 'TIMER_TICK';
export const STARS_NEW_RANDOM = 'STARS_NEW_RANDOM';
export const UPDATE_AVAILABLE_NUMBERS = 'UPDATE_AVAILABLE_NUMBERS';
export const UPDATE_CANDIDATE_NUMBERS = 'UPDATE_CANDIDATE_NUMBERS';
export const CHANGE_DIFFICULTY_LEVEL = 'CHANGE_DIFFICULTY_LEVEL';
